### ISSUE TITLE
update to my issue

### ISSUE THREAD

**Issue by moongazer07** [hnhx/librex#178]
the problem is this ?q=the%20crown&p=0&t=0
it should be like this search.php?q=the+crown&t=0&p=0

help

**Comment by moongazer07** [comment]
[my instance](instance:https://moongazer07.zedekhost.com/search/)

**Comment by amogusussy** [comment]
Is there any reason why you've got two different request methods? On the index.php form, it's POST, but on the search.php form, it's set to GET.

**Comment by moongazer07** [comment]
> Is there any reason why you've got two different request methods? On the index.php form, it's POST, but on the search.php form, it's set to GET.

i wanted to try making it so it does not show up in search history

**Comment by hnhx** [comment]
Yeah the issue is because you use the /search path for LibreX, and the href tags that LibreX use assume that you don't use a path for it, therefore it does .../search.php and in your case it would work like this: .../search/search.php

I will fix this in the next commit, meanwhile you can remove the first `/` letter from the href tags, that will solve the issue.
