### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by carlostkd** [hnhx/librex#214]
Hi 
Its good to see someone developing some tools to protect users privacy , thanks for your project.

But unfortunately i need to say that after looking in the source code and perform some tests on the webapp, she is not privately as the users can think.

The problem:
The app parses the search query's in the url....  doing that  means every librex instance have logs from the users search query's even if its not a option to save logs all logs are saved as default in the webserver where the librex is installed, its ok to say that i dont know whom it belongs the ip address xxxxx but have logs about the query search like "how do that",  "make that" and so on is not good for privacy.

Plus i (and everyone who) hosted the librex can make a php script on top of the search.php to get a lot more infos about the users search querys.

There is many ways to send the search query's direct to the other search engines without parses them in the url  thus avoiding having logs.

Cheers

**Comment by hnhx** [comment]
LibreX supports POST requests as well and the content of POST requests are usually not logged by the webserver, so you can just search with POST requests if you want.

> Plus i (and everyone who) hosted the librex can make a php script on top of the search.php to get a lot more infos about the users search querys.

Yes ofc, there is no way to check the backend of the hosters, however without JS, you can't do much to spy on the users if they use Tor for an example. And since librex is JS free, any instance with JS will be not added to the official list of instances.
