### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by Ahwxx** [hnhx/librex#24]
Are you planning on supporting Docker (or Docker-Compose) in the future?

I'm sorry for asking this here but I couldn't find a better place...

**Comment by hnhx** [comment]
Hey!

I'm sorry but I'm not a big fan of Docker or any other sandbox utility (like flatpak) so no I'm not planning on adding Docker support.

**Comment by tiritibambix** [comment]
[Docker]
❌ Librex
✅ SearxNG
✅Whoogle

**Comment by mariushosting** [comment]
@hnhx Docker support it's mandatory in 2023.

**Comment by Ahwxorg** [comment]
why would anyone use Docker? also you could just get a NGINX Docker container and use that with a config, little more work but if you do need Docker for some reason, do it yourself.

**Comment by tiritibambix** [comment]
> why would anyone use Docker

Docker is a tool that allows you to run different applications in their own little "containers". Think of it like a mini-computer inside your regular computer.

Imagine you want to run two different websites on your computer, but they both need different versions of a programming language or different settings. If you run them directly on your computer, they might clash and not work properly.

With Docker, you can put each website in its own container, and it will run separately from the other containers. This way, the two websites won't interfere with each other and will work smoothly.

Another benefit of Docker is that it makes it easy to move your applications to different computers or servers. You can just take the container and drop it on another machine, and it will run the same way as it did on your original computer.

In simple words, Docker is like a way to keep different applications separated, so they don't interfere with each other, and it makes it easy to move them around.

So, why would anyone use Docker were you asking ? Because it's easy to use and convenient, and you don't have to like it for others to use it.

I hope that helped :)

**Comment by Ahwxorg** [comment]
I am not here to discuss things, and I am not going to, but I personally don't think you should use Docker for this kind of thing. You should run multiple users and ideally VMs in my opinion. Again, opinions.
